### ISSUE TITLE
CRC release to-do

### ISSUE THREAD

**Issue by ismayc** [moderndive/ModernDive_book#249]
- [x] Start TOC on page v
- [x] Make sure floats (images/tables) follow soon after code creation
     - [x] Try to minimize white space (force figures and tables and get them to match up as needed)
- [x] Add mention of `pivot_wider()` to Chapter 4
- [x] Check table captions throughout the book to ensure they *don’t* have a period ending them
- [x] Check figures captions throughout the book to ensure they *do* have a period ending them
- [x] Check for spacing of figures and text at the top of the page as noted by CRC review
- [x] Convert Appendix B (R Packages) into multiple tables per sheet (not needed after focusing on only book packages)
- [x] Anywhere `knitr::kable(booktabs = TRUE)`, add `linesep = ""`
- [x] Add location and publisher information for physical books (not packages) to `bib/*.bib` files
- [x] In PDF Section 3.8, check Wikipedia entry for SQL in footnote being on the correct page 
- [x] Create `geom_parallel_slopes()`
- [x] Chester adds bio to “About the authors” section
- [x] Chester adds to dedication page in PDF if he wants
- [x] Address `TODO` in `.Rmd` files
- [x] Fix issue #232 in Hypothesis Testing
- [x] Appendix numbering to include “Appendix” before “A” and “B” (Waiting on CRC for LaTeX fix)
    - [x] Not show “Appendix” as a heading in TOC by itself as is currently done
- [x] Do a second pass over CRC’s proofreading included in their PDF. Red are left-over deletions, blue are left-over suggestions, Yellow means done, green means no way in response to their blue/red.
- [x] Check that each page has a running header at the top.
- [x] Add mention of red and white balls from the cover in Chapter 7 are shown in black/white in text, embedded in knitr::is_latex since this is only relevant for print edition.
- [x] Add mention of blue hex sticker on cover in Preface/Foreword & change link to blue hex sticker
- [x] Edit `index.Rmd` & `00-preface.Rmd` (in `v1.0.0` branch) so that text reflects release version 1.0.0, but do not merge branch into `master` until CRC gives final green light.
- [x] Search for ?? in book
- [x] Check that any hardcoded calculations have the correct numbers from Ch5 on. 
- [x] One last spellcheck of each chapter
- [x] Scan over the PDF output one last time

**Comment by rudeboybert** [comment]
- [ ] Chester will XeLaTex the contents of [Google Drive](https://drive.google.com/drive/u/0/folders/1P5K8YJyiLwu9D-HIaYFvVY6d-cAn1DKh) and see if his outputted PDF matches the one Albert XeLaTeX'ed. If they don't match, we'll need to tell CRC press that they need to ensure that there is no trapped-whitespace

**Comment by rudeboybert** [comment]
- [ ] After we get final green light from CRC press but before we update `release` branch, change currently hardcoded v1.0.0 release date`"November 25, 2019"` to whatever date we update moderndive.com
